[package]
name = "sioyek-dict"
version = "0.2.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
zip = "2"
nlprule-build = "0.6.4"

[dependencies]
wordnet-db = "0.1"
wordnet-types = "0.1"
nlprule = "0.6.4"

[profile.release]
opt-level = "z"
lto = true
strip = true
